version: '3'
services:
  odoo10-db:
    image: postgres:9.4-alpine
    restart: always
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=odoo"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - odoo10_db:/var/lib/postgresql/data/pgdata
#    network:
#      - odoo10_network
  odoo10:
    build: .
    depends_on:
      - odoo10-db
    ports:
      - "8071:8069"
    environment:
      - "HOST=odoo10-db"
      - "USER=odoo"
      - "PASSWORD=password"
    volumes:
      - /srv/odoo10/odoo:/etc/odoo
      - odoo10_addons:/mnt/extra-addons
      - odoo10_data:/var/lib/odoo
#    network:
#      - odoo10_network     
#networks:
#  odoo10_network:
#    driver: bridge
#    attachable: false
volumes:
  odoo10_data:
  odoo10_addons:
