version: '3'
services:
  odoo-db:
    image: postgres:10-alpine
    restart: always
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=odoo"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - /srv/odoo/db:/var/lib/postgresql/data/pgdata
    network:
      - odoo11_network
  odoo:
    build: .
#   depends_on:
#      - odoo-db
    ports:
      - "8072:8069"
    environment:
      - "HOST=odoo-db"
      - "USER=odoo"
      - "PASSWORD=password"
    volumes:
      - /srv/odoo/odoo:/etc/odoo
      - /srv/odoo/addons:/mnt/extra-addons
      - odoo11_data:/var/lib/odoo
     network:
      - odoo11_network     
 networks:
   odoo11_network:
     driver: bridge
     attachable: false
