version: '2'
services:
  odoo-db:
    image: postgres:10-alpine
    restart: always
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=odoo"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - /srv/odoo/db:/var/lib/postgresql/data/pgdata

